server:
  http_listen_port: 9080

clients:
  - url: "http://loki:3100/loki/api/v1/push"

scrape_configs:
  - job_name: "session-service-logs"
    static_configs:
      - labels:
          job: "session-service"
          host: "session-service-container"
          __path__: "/workdir/app.log"
