{
 "title": "task2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Количество нод",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество контейнеров",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доступность google.com",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", instance=\"142.250.190.78\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Затраченная RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\"} / (1024*1024*1024) - node_memory_MemFree_bytes{job=\"node-exporter\"} / (1024*1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Использование CPU по сервисам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name!=\"\", container_label_com_docker_compose_project=\"src\"}[1m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Доступная память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{job=\"node-exporter\"} / (1024*1024*1024)) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование CPU по ядрам и узлам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\"}[1m])) by (instance, cpu)",
     "legendFormat": "Instance:{{instance}} CPU:{{cpu}}"
    }
   ]
  },
  {
   "title": "Количество отправленных сообщений в rabbitmq",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_messages_sent_total{job=\"micrometer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество обработанных сообщений в rabbitmq",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_messages_processed_total{job=\"micrometer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество бронирований",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hotel_bookings_total{job=\"micrometer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество полученных запросов на gateway",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "requests_received_gateway_total{job=\"micrometer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество полученных запросов на авторизацию пользователей",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_authorization_requests_total{job=\"micrometer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Логи приложения",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/workdir/app.log\"} |= ``"
    }
   ]
  }
 ]
}