global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.100.100:9100']
      - targets: ['192.168.100.101:9100']
      - targets: ['192.168.100.102:9100']

  - job_name: 'micrometer'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['report-service:8086']
      - targets: ['booking-service:8083']
      - targets: ['gateway-service:8087']
      - targets: ['session-service:8081']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://gateway-service:8087
        - http://session-service:8081
        - 142.250.190.78

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.100.100:8100']
      - targets: ['192.168.100.101:8100']
      - targets: ['192.168.100.102:8100']

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093